---
title: "P8105_final_project"
author: "Hao Zheng (hz2770), Peilin Zhou (pz2281), Xiao Ma(xm2276), Yida Wang(yw3774), Ruilian Zhang (rz2570)"
date: "11/11/2021"
output: github_document
---

```{r setup, message = FALSE}
library(tidyverse)
library(rvest)
library(knitr)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```
Load the dataset NYPD shooting incident
```{r}
shooting = 
  read_csv("./data/NYPD_Shooting.csv") %>%
  janitor::clean_names()
```
check null
```{r}
shooting %>%
  summarise_all(~ sum(is.na(.)))
```
For col boro
```{r}
shooting = shooting %>% 
  mutate(boro = as.factor(boro)) %>%
  mutate(location_desc = replace_na(location_desc, "NONE")) %>%
  mutate(location_desc = as.factor(location_desc)) %>%
  mutate(location_desc = fct_relevel(location_desc, c("NONE", "MULTI DWELL - PUBLIC HOUS", "MULTI DWELL - APT BUILD", "PVT HOUSE", "GROCERY/BODEGA", "BAR/NIGHT CLUB", "HOSPITAL", "COMMERCIAL BLDG", "DEPT STORE", "GAS STATION", "HOTEL/MOTEL", "SMALL MERCHANT", "RESTAURANT/DINER", "CLOTHING BOUTIQUE", "FACTORY/WAREHOUSE", "SOCIAL CLUB/POLICY LOCATI"))) %>%
  mutate(location_desc = recode(location_desc, 
                                "NONE" = "none",
                                "MULTI DWELL - PUBLIC HOUS" = "public_house", 
                                "MULTI DWELL - APT BUILD" = "apt_building", 
                                "PVT HOUSE" = "pirvate_house", 
                                "GROCERY/BODEGA" = "grocery_bodega", 
                                "BAR/NIGHT CLUB" = "bar_club",
                                "HOSPITAL" = "hospital",
                                "COMMERCIAL BLDG" = "commercial",
                                "DEPT STORE" = "dept_store",
                                "GAS_STATION" = "gas_station",
                                "HOTEL/MOTEL" = "hotel",
                                "SMALL MERCHANT" = "merchant",
                                "RESTAURANT/DINER" = "restaurant",
                                "CLOTHING BOUTIQUE" = "clothing",
                                "FACTORY/WAREHOUSE" = "factory",
                                "SOCIAL CLUB/POLICY LOCATI" = "club"
                                )) %>%
  separate(occur_date, into = c("month", "day", "year")) %>% 
  mutate(month = as.numeric(month)) %>% 
  arrange(year, month) %>% 
 # mutate(month = month.name[month]) %>% 
  mutate(year = as.character(year)) %>% 
  mutate(boro = tolower(boro)) %>% 
  mutate(boro = if_else(boro == "staten island", "staten_island", boro)) %>% 
  rename(borough = boro) %>% 
    mutate(date = str_c(month, day, year, sep = "/")) %>% 
  select(incident_key, date, everything())
```  

Next, clean the COVID-19 case count data

Importing COVID-19 case count data

```{r}
covid_counts = read.csv("./data/COVID19_data.csv", sep = ";") %>% as_tibble()
```

The clean dataset contains only day-by-day COVID-19 case count for each borough and the total case count in NYC of a particular day.
```{r}
clean_covid = covid_counts %>% 
   janitor::clean_names() %>% 
   rename(date = date_of_interest) %>% 
   select(date, contains("case_count")) %>% 
   select(-contains(c("probable_case_count", "case_count_7day_avg", "all_case_count_7day_avg"))) %>%
   separate(date, into = c("month", "day", "year")) %>% 
   mutate_all(as.character) %>% 
   mutate_if(is.character, gsub, pattern = ",", replacement = "") %>% 
   mutate_if(is.character, as.numeric) %>%
   pivot_longer(
    cols = bx_case_count:si_case_count,
    names_to = "borough",
    values_to = "borough_case_count"
  ) %>% 
  mutate(borough = gsub("_case_count", "", borough)) %>% 
  mutate(borough = recode(borough, "bx" = "bronx","bk" = "brooklyn","mn" = "manhattan","si" = "staten_island","qn" = "queens")) %>% 
  relocate(case_count, .after = borough_case_count) %>% 
  rename(total_case_count = case_count) %>% 
  mutate(date = str_c(month, day, year, sep = "/")) %>% 
  select(date, everything())

head(clean_covid)
```
