---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
runtime: shiny
---

```{r setup, include = FALSE}
library(flexdashboard)
library(tidyverse)
library(leaflet)
library(rgdal)
library(shiny)
library(plotly)
```

```{r, include = FALSE}
shooting_initial = 
  read_csv("nypd_shooting.csv") %>% janitor::clean_names()
shooting_2021 = read_csv("nypd_shooting_new.csv") %>% janitor::clean_names()
shooting_2021 = shooting_2021 %>% 
  rename(lon_lat = new_georeferenced_column)

shooting = rbind(shooting_initial, shooting_2021)

shooting = shooting %>% 
  mutate(boro = as.factor(boro)) %>%
  mutate(location_desc = replace_na(location_desc, "NONE")) %>%
  mutate(location_desc = as.factor(location_desc)) %>%
  separate(occur_date, into = c("month", "day", "year")) %>% 
  mutate(month = as.numeric(month)) %>% 
  arrange(year, month) %>% 
 # mutate(month = month.name[month]) %>% 
  mutate(year = as.character(year)) %>% 
  mutate(boro = tolower(boro)) %>% 
  mutate(boro = if_else(boro == "staten island", "staten_island", boro)) %>% 
  rename(borough = boro) %>% 
  mutate(date = str_c(month, day, year, sep = "/")) %>% 
  select(incident_key, date, everything())

shooting_map = shooting %>% 
  mutate_at(c("perp_age_group", "perp_sex", "perp_race"), funs(ifelse(is.na(.), "unknown", .))) %>% 
  mutate(labels = str_c("<b>Incident Key: </b>", incident_key, 
                    "<br>", "<b>Date: </b>", date,
                    "<br>", "<b>Borough: </b>", borough,
                    "<br>", "<b>Murdered: </b>", statistical_murder_flag,
                    "<br>", "<b>Perpetrator's Race: </b>", perp_race,
                    "<br>", "<b>Victim's Race: </b>", vic_race,
                    "<br>", "<b>Perpetrator's Age: </b>", perp_age_group,
                    "<br>", "<b>Victim's Age: </b>", vic_age_group
                    ))

nyc_boro = readOGR("geo_export_2204bc6b-9c17-46ed-8a67-7245a1e15877.shp", layer = "geo_export_2204bc6b-9c17-46ed-8a67-7245a1e15877")
```  


Column {.sidebar}
-----------------------------------------------------------------------

```{r, message=FALSE, warning=FALSE}
boro = shooting %>% 
  distinct(borough) %>% 
  pull()

selectInput(
  "borough_choice",
  label = h2("Select Borough"),
  choices = boro,
  selected = "manhattan"
)

race = shooting %>% 
  mutate(perp_race = ifelse(is.na(perp_race), "UNKNOWN", perp_race)) %>% 
  distinct(perp_race) %>% 
  pull()

selectInput(
  "perprace_choice",
  label = h2("Select Perpetrators' Race"),
  choices = race,
  selected = "Black"
)

max_year = shooting %>% 
  mutate(year = as.numeric(year)) %>% 
  distinct(year) %>% 
  max()

min_year = shooting %>% 
  mutate(year = as.numeric(year)) %>% 
  distinct(year) %>% 
  min()

sliderInput(
  "year_choice",
  label = h2("Year Range"),
  min = min_year,
  max = max_year,
  value = c(2016,2021)
)

```

```{r import and merge covid data}
covid_counts = read.csv("covid19_data.csv", sep = ";") %>% as_tibble()

clean_covid = covid_counts %>% 
   janitor::clean_names() %>% 
   rename(date = date_of_interest) %>% 
   select(date, contains("case_count")) %>% 
   select(-contains(c("probable_case_count", "case_count_7day_avg", "all_case_count_7day_avg"))) %>%
   separate(date, into = c("month", "day", "year")) %>% 
   mutate_all(as.character) %>% 
   mutate_if(is.character, gsub, pattern = ",", replacement = "") %>% 
   mutate_if(is.character, as.numeric) %>%
   pivot_longer(
    cols = bx_case_count:si_case_count,
    names_to = "borough",
    values_to = "borough_case_count"
  ) %>% 
  mutate(borough = gsub("_case_count", "", borough)) %>% 
  mutate(borough = recode(borough, "bx" = "bronx","bk" = "brooklyn","mn" = "manhattan","si" = "staten_island","qn" = "queens")) %>% 
  relocate(case_count, .after = borough_case_count) %>% 
  rename(total_case_count = case_count) %>% 
  mutate(date = str_c(month, day, year, sep = "/")) %>% 
  select(date, everything())

shooting_mini =
  shooting %>% 
  filter(year == "2020") %>% 
  select(c("date", "incident_key", "borough"))

shooting_covid = 
  merge(x = shooting_mini, y = clean_covid, by = c("date", "borough")) %>% 
  relocate("date", "month", "day", "year", everything()) %>% 
  group_by(date) %>% 
  add_count(borough, name = "borough_n_victim") %>% # victim number equals to the count of incident_key (includind duplicate)
  distinct() %>% 
  add_count(borough, name = "borough_n_shooting") %>% # shooting number equals to the count of distinct incident_key
  select(-incident_key) %>% 
  distinct() %>% 
  add_count(date, wt = borough_n_victim, name = "total_n_victim") %>% 
  add_count(date, wt = borough_n_shooting, name = "total_n_shooting") %>% 
  mutate(
    borough = recode(borough, 
                     "bronx" = "Bronx",
                     "brooklyn" = "Brooklyn",
                     "manhattan" = "Manhattan",
                     "queens" = "Queens",
                     "staten_island" = "Staten Island")
  )
```

```{r build menu for shooting_covid data}
sliderInput(
  "covid_case_range",
  label = h3("COVID Case Range"),
  min = 1,
  max = 6129,
  value = c(100, 6000)
)
```



Map of Shooting Incidents in NYC {data-width=650}
-----------------------------------------------------------------------

### Shooting Incidents Across Space

```{r, map_shooting}

renderLeaflet({

  shooting_map %>% 
    filter(
      borough == input$borough_choice,
      year == input$year_choice
    ) %>% 
    leaflet() %>% 
    addTiles() %>% 
    addProviderTiles("CartoDB.Positron") %>% 
    addMarkers(lng = ~longitude, lat = ~latitude, popup = ~labels,
               clusterOptions = markerClusterOptions()) %>% 
    addPolygons(data = nyc_boro,
                weight = 0.85,
                label = ~nyc_boro@data$boro_name)
})
```

Column {data-width=350}
-----------------------------------------------------------------------

### Perpetrators' race across space

```{r map perpetrator race}
renderLeaflet({

  shooting_map %>% 
    filter(
      perp_race == input$perprace_choice,
      year == input$year_choice
    ) %>% 
    leaflet() %>% 
    addTiles() %>% 
    addProviderTiles("CartoDB.Positron") %>% 
    addMarkers(lng = ~longitude, lat = ~latitude, popup = ~labels,
               clusterOptions = markerClusterOptions()) %>% 
    addPolygons(data = nyc_boro,
                weight = 0.85,
                label = ~nyc_boro@data$boro_name)
})
```

### Shooting incidence and COVID Cases

```{r plotly plot for covid_shooting}
renderPlotly({
  
  shooting_covid %>% 
    plot_ly(
      x = ~total_case_count, y = ~total_n_shooting,
      type = "scatter", mode = "markers",
           color = ~borough, alpha = .8) %>% 
    layout(
      title = "Distribution of Shooting Cases Against COVID Cases Within Each Day",
      xaxis = list(title = "Total COVID Cases"),
      yaxis = list(title = "Total Shooting Cases"))
    
  
})
```






